ttheme: jekyll-theme-merlot
title: ARRIVED HOME
description: "Mindfulness is the energy of being aware and awake to the present moment. It is the continuous practice of touching life deeply in every moment of daily life. To be mindful is to be truly alive, present, and at one with those around you and with what you are doing. We bring our body and mind into harmony while we wash the dishes, drive the car, or take our morning shower."
email: "sunnynaidu1970@gmail.com"
webserver: "https://deerparkmonastery.org/"
